server:
  port: 8080

frontend:
  base-url: http://localhost:3000

cors:
  allowed-origins: >
    http://localhost:3000,
    https://med-connect-psi-nine.vercel.app,
    https://med-connect-b9bmw148l-bobi759s-projects.vercel.app

spring:
  application:
    name: springSecFinal

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  message: ${JWT_MESSAGE}

gemini:
  api-key: ${GOOGLE_GEMINI_KEY}
  url: ${GEMINI_URL}

stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    phone-number: ${TWILIO_PHONE_NUMBER}
    messaging-service-sid: ${TWILIO_MESSAGING_SERVICE_SID}
